// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rbind_ident_in_place
arma::vec rbind_ident_in_place(arma::vec& ident, int n, const arma::vec& new_ident);
RcppExport SEXP _TRSwapping_rbind_ident_in_place(SEXP identSEXP, SEXP nSEXP, SEXP new_identSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type ident(identSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type new_ident(new_identSEXP);
    rcpp_result_gen = Rcpp::wrap(rbind_ident_in_place(ident, n, new_ident));
    return rcpp_result_gen;
END_RCPP
}
// length_inter
int length_inter(const arma::mat& mat, const arma::uvec& col_idx, const arma::vec& vec);
RcppExport SEXP _TRSwapping_length_inter(SEXP matSEXP, SEXP col_idxSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type col_idx(col_idxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(length_inter(mat, col_idx, vec));
    return rcpp_result_gen;
END_RCPP
}
// drawC
List drawC(const arma::mat& st_mat, const arma::mat& r_mat, const arma::mat& d_mat);
RcppExport SEXP _TRSwapping_drawC(SEXP st_matSEXP, SEXP r_matSEXP, SEXP d_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type st_mat(st_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type r_mat(r_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d_mat(d_matSEXP);
    rcpp_result_gen = Rcpp::wrap(drawC(st_mat, r_mat, d_mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TRSwapping_rbind_ident_in_place", (DL_FUNC) &_TRSwapping_rbind_ident_in_place, 3},
    {"_TRSwapping_length_inter", (DL_FUNC) &_TRSwapping_length_inter, 3},
    {"_TRSwapping_drawC", (DL_FUNC) &_TRSwapping_drawC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_TRSwapping(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
