// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// drawC
List drawC(IntegerVector st_sim, IntegerVector st_geo, IntegerVector st_geo_sup, IntegerVector r_ident, IntegerVector r_sim, IntegerVector r_geo, IntegerVector r_geo_sup, IntegerVector d_ident, IntegerVector d_sim, IntegerVector d_geo, IntegerVector d_geo_sup);
RcppExport SEXP _TRSwapping_drawC(SEXP st_simSEXP, SEXP st_geoSEXP, SEXP st_geo_supSEXP, SEXP r_identSEXP, SEXP r_simSEXP, SEXP r_geoSEXP, SEXP r_geo_supSEXP, SEXP d_identSEXP, SEXP d_simSEXP, SEXP d_geoSEXP, SEXP d_geo_supSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type st_sim(st_simSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type st_geo(st_geoSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type st_geo_sup(st_geo_supSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type r_ident(r_identSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type r_sim(r_simSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type r_geo(r_geoSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type r_geo_sup(r_geo_supSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d_ident(d_identSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d_sim(d_simSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d_geo(d_geoSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d_geo_sup(d_geo_supSEXP);
    rcpp_result_gen = Rcpp::wrap(drawC(st_sim, st_geo, st_geo_sup, r_ident, r_sim, r_geo, r_geo_sup, d_ident, d_sim, d_geo, d_geo_sup));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TRSwapping_drawC", (DL_FUNC) &_TRSwapping_drawC, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_TRSwapping(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
