# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

drawC <- function(st_sim, st_geo, st_geo_sup, r_ident, r_sim, r_geo, r_geo_sup, d_ident, d_sim, d_geo, d_geo_sup) {
    .Call('_TRSwapping_drawC', PACKAGE = 'TRSwapping', st_sim, st_geo, st_geo_sup, r_ident, r_sim, r_geo, r_geo_sup, d_ident, d_sim, d_geo, d_geo_sup)
}

