# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rbind_idx_in_place <- function(idx, n, new_idx) {
    .Call(`_TRSwapping_rbind_idx_in_place`, idx, n, new_idx)
}

rbind_ident_in_place <- function(ident, n, new_ident) {
    .Call(`_TRSwapping_rbind_ident_in_place`, ident, n, new_ident)
}

find_idx <- function(ident, ident_drawn) {
    .Call(`_TRSwapping_find_idx`, ident, ident_drawn)
}

drawC <- function(st_mat, r_mat, d_mat) {
    .Call(`_TRSwapping_drawC`, st_mat, r_mat, d_mat)
}

